### ISSUE TITLE
Não está mais funcionando

### ISSUE THREAD

**Issue by roger-net** [byosni/azuracast#1]
Estava usando por um tempo mais de um tempo pra cá não funciona mais. Esse é o erro que acontece.

 https://agenciabrasil.ebc.com.br/sites/default/files/atoms/audio/
Resolving agenciabrasil.ebc.com.br (agenciabrasil.ebc.com.br)... 2600:1408:5400:d::170c:9384, 2600:1408:5400:d::170c:9396, 23.205.106.79, ...
Connecting to agenciabrasil.ebc.com.br (agenciabrasil.ebc.com.br)|2600:1408:5400:d::170c:9384|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-20 15:20:50 ERROR 404: Not Found.

**Comment by byosni** [comment]
Poderia testar novamente, o problema estava na fonte da noticia.
